#!/usr/bin/env python3
"""Regenerate llms.txt for flaven.fr from the staging database.

Usage:  python3 tools/generate_llms_txt.py > wordpress/llms.txt
Then upload wordpress/llms.txt to the site root (next to robots.txt).

Reads wp_posts through the docker MySQL container (wp_docker-db-1,
database wordpress2), so `docker compose up -d` must be running and the
staging DB must hold a fresh prod dump. Static sections (Code, Optional)
are maintained inline below — edit them here when the GitHub/social
lists change.
"""

import html
import re
import subprocess
import sys

SITE = "https://flaven.fr"
EXCERPT_LEN = 150

HEADER = f"""# Bruno Flaven's website

> Professional blog of Bruno Flaven, currently working as AI Coordinator with over 20 years' experience. More at [flaven.fr]({SITE}) or [LinkedIn](https://www.linkedin.com/in/brunoflaven).

## Homepage
- [Homepage]({SITE}): Bruno Flaven's personal and professional articles on AI, mobile, and digital product management.

## AI agent access
- [WebMCP manifest]({SITE}/wp-json/webmcp/v1/manifest): machine-readable tool manifest (WebMCP proposed standard) exposing search_posts, get_latest_posts, list_categories, get_post_toc and get_related_posts REST endpoints under {SITE}/wp-json/webmcp/v1/.
- [RSS feed]({SITE}/feed/): latest posts.
- [Sitemap]({SITE}/sitemap.xml): full URL inventory.
"""

COLLECTIONS = f"""
## Content collections
- [Quotes]({SITE}/publications/): curated quotes archive (authors, flavors taxonomies).
- [Videos]({SITE}/videos/): YouTube videos archive with categories and tags.
- [Clients]({SITE}/clients/): client references with expertises and languages.
"""

PAGES = f"""
## Pages
- [My resume]({SITE}/bruno-flaven-resume-cv/)
- [Publications]({SITE}/publications/)
- [Videos]({SITE}/videos/)
- [3WDOC]({SITE}/about-3wdoc/)
"""

CODE_AND_OPTIONAL = """
## Code
- Shared scripts, code samples, and project demos in the articles and blog posts.
- [ia_usages](https://github.com/bflaven/ia_usages): An overview of the possibilities offered by artificial intelligence (AI) to serve as a technical basis for a digital product offering: from understanding, personalization, design of machine learnin…
- [ia_formation_tunisia](https://github.com/bflaven/ia_formation_tunisia)
- [learning_python_for_all](https://github.com/bflaven/learning_python_for_all): A set of resources from Books, Exercises, Notebooks to discover and learn Python. It exists both in French and in English.
- [xml_archive_wordpress](https://github.com/bflaven/xml_archive_wordpress): Parse an xml wordpress archive with python
- [PluginWordpressForFun](https://github.com/bflaven/PluginWordpressForFun): Some plugins for wordpress, sometimes used for fun or on flaven.fr
- [ia_usages_code_depot](https://github.com/bflaven/ia_usages_code_depot): An archive directory of all the code used for the different POCS on AI
- [BlogArticlesExamples](https://github.com/bflaven/BlogArticlesExamples): Some code extracted from articles released on flaven.fr
- [book-defining-testing-strategy-agile-po-codeception](https://github.com/bflaven/book-defining-testing-strategy-agile-po-codeception): Defining a testing automation strategy for a P.O. with CODECEPTION_ & WordPress
- [methodological_survival_kit](https://github.com/bflaven/methodological_survival_kit): A set of three personal presentations in French and in PDF that provides a tiny methodological survival kit: from agile Scrum method for project management to Corporate Hacking or Culture Hacking w…
- [new_powers_new_responsibilities_the_journalism_ai_report](https://github.com/bflaven/new_powers_new_responsibilities_the_journalism_ai_report): Une synthèse d'un excellent document disponible en ligne, relativement récent (2019) extrait du "The JournalismAI Report", nommé "New powers, new responsibilities. A global survey of journalism and…

## Optional
- [LinkedIn profile](https://www.linkedin.com/in/brunoflaven)
- [Youtube](https://www.youtube.com/channel/UCnUBoVx9Yai3wirPBvNpNQw)
- [Github](https://github.com/bflaven/)
- [Amazon](https://amzn.to/2WQbRpA)
[comment]: # (Generated by tools/generate_llms_txt.py for flaven.fr)
"""


def fetch_posts():
    """Return [(title, url, excerpt)] for published posts, newest first."""
    query = (
        "SELECT ID, post_title, post_name, DATE_FORMAT(post_date,'%Y/%m'), post_content "
        "FROM wp_posts WHERE post_type='post' AND post_status='publish' "
        "ORDER BY post_date DESC;"
    )
    # Old posts mix cp1252 bytes (em-dash 0x97, curly quotes) into the
    # utf-8 stream: decode utf-8 first, map the leftovers via cp1252.
    raw = subprocess.run(
        ["docker", "exec", "wp_docker-db-1", "mysql", "-uroot", "-proot",
         "wordpress2", "--batch", "--raw=0", "-N", "-e", query],
        capture_output=True, check=True,
    ).stdout
    out = raw.decode("utf-8", errors="surrogateescape")
    out = "".join(
        bytes([ord(c) - 0xDC00]).decode("cp1252", errors="replace")
        if 0xDC80 <= ord(c) <= 0xDCFF else c
        for c in out
    )
    posts = []
    for line in out.splitlines():
        parts = line.split("\t", 4)
        if len(parts) != 5:
            continue
        _id, title, slug, yyyymm, content = parts
        posts.append((clean_text(title), f"{SITE}/{yyyymm}/{slug}/", excerpt(content)))
    return posts


def clean_text(text):
    """Unescape mysql batch escapes and HTML entities, strip tags."""
    text = text.replace("\\n", " ").replace("\\t", " ").replace("\\\\", "\\")
    text = re.sub(r"\[/?[a-zA-Z][^\]]*\]", " ", text)  # shortcodes
    text = re.sub(r"<[^>]+>", " ", text)               # tags
    text = html.unescape(text)
    return re.sub(r"\s+", " ", text).strip()


def excerpt(content):
    return clean_text(content)[:EXCERPT_LEN]


def main():
    posts = fetch_posts()
    if not posts:
        sys.exit("no posts fetched - is docker up with the prod dump loaded?")
    lines = [HEADER, "## Posts"]
    for title, url, snippet in posts:
        lines.append(f"- [{title}]({url}): {snippet}")
    lines += [COLLECTIONS.rstrip(), PAGES.rstrip(), CODE_AND_OPTIONAL.rstrip(), ""]
    sys.stdout.write("\n".join(lines))
    print(f"\n", end="")
    print(f"generated: {len(posts)} posts", file=sys.stderr)


if __name__ == "__main__":
    main()
